prow.sh: remove Bazel build support
In KinD 0.11.0, --type=bazel triggers an error:
   ERROR: --type is no longer supported, please remove this flag

This broke Prow jobs with CSI_PROW_KUBERNETES_VERSION=release-1.[18|19|20].